<?php
/**
 * Created by PhpStorm.
 * User: 周子健
 * Date: 2017/8/17
 * Time: 18:01
 */

namespace backend\models;


use yii\base\Model;

class ModifyFrom extends  Model
{
    //旧密码
    public $Oldpassword;
    //旧密码
    public $Newpassword;
    //定义确认密码
    public $password_confirm;


    public function rules()
    {
        return [
            [['Oldpassword','Newpassword','password_confirm'],'required'],
            [['password_confirm'],'compare',
                'compareAttribute'=>'Newpassword',
                'operator'=>'===',
                'message'=>'两次密码必须一致'],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'password_confirm'=>'确认密码',
            'Newpassword'=>'新密码',
            'Oldpassword'=>'旧密码',

        ]; // TODO: Change the autogenerated stub
    }

}