<?php


namespace backend\models;


use yii\base\Model;

class ParmissionFrom extends Model
{
    public $name;
    public $description;

    public function rules()
    {
        return [
          [['name','description'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'name' => '路由',
            'description'=> '描述'
        ]; // TODO: Change the autogenerated stub
    }

    public function Parmissionsave()
    {
        //实例authManager对象
        $authManager = \Yii::$app->authManager;
        if ($authManager->getPermission($this->name)){
            //添加错误信息
            $this->addError('name','该权限已存在');
        }else{
            //添加权限
            $parmission = $authManager->createPermission($this->name);
            $parmission->description = $this->description ;
            //保存权限
            $authManager->add($parmission);
            return true;
        }

    }


    public function Parmissionedit($parmissionName)
    {
        //实例authManager对象
        $authManager = \Yii::$app->authManager;
        //实例authManager对象
        $parmission = \Yii::$app->authManager->getPermission($parmissionName);
         //判定当前的权限名是否和该对象的权限名一致只修改描述
        if ($parmissionName == $this->name){
            $parmission->description = $this->description;
            $authManager->update($this->name,$parmission);
            return true;
        } else{
            //判定当前修改的权限名是否已经存在,存在添加错误信息返回false
          if ($authManager->getPermission($this->name)){
              $this->addError('name','权限已存在');
              return false;
          }else{
              //否则修改权限及描述并保存
              $parmission->name = $this->name;
              $parmission->description = $this->description;
              //修改权限
              $authManager->update($parmissionName,$parmission);
              return true;
          }
        }
    }



}